[project]
name = "pychercheur"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "firecrawl-py>=1.12.0",
    "litellm>=1.61.16",
    "requests>=2.32.3",
    "streamlit>=1.42.2",
]
